# -*- coding: utf-8 -*-
"""Lab3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17x-WXDL0QmcR4_0KsQKveSPDXK3F8LLU
"""

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Activation, Dense
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np

# Collect data and then convert target column letters to 0 or 1
dataset = pd.read_csv("breastcancer.csv",skiprows=1, header=None).replace({'M': 0, "B": 1})

sc = StandardScaler()
# Normalize the Data
scaled = sc.fit_transform(dataset.iloc[:,2:32])
print(scaled)
# Split into sets
X_train, X_test, Y_train, Y_test = train_test_split(scaled, dataset.iloc[:,1],
                                                    test_size=0.25, random_state=87)
# Run NN
np.random.seed(155)
my_first_nn = Sequential() # create model
my_first_nn.add(Dense(20, input_dim=30, activation='relu')) # hidden layer
my_first_nn.add(Dense(20, activation='relu')) # hidden layer
my_first_nn.add(Dense(1, activation='sigmoid')) # output layer
my_first_nn.compile(loss='binary_crossentropy', optimizer='adam', metrics=['acc'])
my_first_nn_fitted = my_first_nn.fit(X_train, Y_train, epochs=100,
                                     initial_epoch=0)
print(my_first_nn.summary())
print(my_first_nn.evaluate(X_test, Y_test))